package com.jamesm92.nomadportal.ui.components

import android.graphics.Bitmap
import android.graphics.Color as AndroidColor
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel

/**
 * Renders [content] as a black-on-white QR bitmap, [sizePx] square.
 * Pure ZXing-core (`com.google.zxing:core`), no Android-specific wrapper
 * needed for encoding — just a `BitMatrix` painted pixel-by-pixel into a
 * plain [Bitmap]. See `libs.versions.toml`'s own comment for why ZXing
 * over ML Kit (no Google-Play-Services dependency anywhere else in this
 * app, and this keeps it that way).
 *
 * [content] is normally [buildIdentityQrPayload]'s output — see that
 * function's own doc comment for the real format and why it carries more
 * than just the raw address.
 */
fun generateQrBitmap(content: String, sizePx: Int = 512): Bitmap {
    val hints = mapOf(EncodeHintType.ERROR_CORRECTION to ErrorCorrectionLevel.M)
    val matrix = QRCodeWriter().encode(content, BarcodeFormat.QR_CODE, sizePx, sizePx, hints)
    val bitmap = Bitmap.createBitmap(sizePx, sizePx, Bitmap.Config.RGB_565)
    for (x in 0 until sizePx) {
        for (y in 0 until sizePx) {
            bitmap.setPixel(x, y, if (matrix.get(x, y)) AndroidColor.BLACK else AndroidColor.WHITE)
        }
    }
    return bitmap
}

/** `lxma://<destination_hash_hex>:<public_key_hex>` — Columba's own real
 * QR payload format for identity sharing (confirmed directly against its
 * source, `network.columba.app.util.IdentityQrCodeUtils`, during a fresh
 * Columba-parity-audit pass — not guessed, and adopted verbatim rather
 * than inventing an incompatible scheme, so a code generated by either
 * app scans correctly in the other).
 *
 * Carrying the public key alongside the hash (not just the hash, which
 * is what this app's QR code originally encoded) is the real reason this
 * format exists: it lets the scanning device register the identity
 * immediately via `RNS.Identity.remember()`
 * ([com.jamesm92.nomadportal.data.messaging.MessagingRepository.importScannedContact]),
 * without waiting to hear a real mesh announce from that peer first — see
 * that function's own doc comment (and `messaging.py`'s
 * `import_scanned_contact`, the Python side of the same mechanism) for
 * the full reliability rationale. */
fun buildIdentityQrPayload(destinationHash: String, publicKeyHex: String): String =
    "lxma://$destinationHash:$publicKeyHex"

/** The destination hash and public key decoded from an
 * [buildIdentityQrPayload]-shaped scan, or null if [text] doesn't match
 * that shape (including plain hex from before this format existed, or a
 * QR code from something other than this app's own identity-sharing
 * flow) — [QrScannerOverlay] falls back to treating such text as a bare
 * address instead, same as manual entry always has. */
data class ScannedIdentity(val destinationHash: String, val publicKeyHex: String?)

fun parseIdentityQrPayload(text: String): ScannedIdentity? {
    val body = text.trim().removePrefix("lxma://")
    if (body == text.trim()) return null // no prefix present at all
    val parts = body.split(":")
    if (parts.size != 2) return null
    val (hash, pubKey) = parts
    val isValidHex = { s: String -> s.isNotEmpty() && s.length % 2 == 0 && s.all { it in "0123456789abcdefABCDEF" } }
    if (!isValidHex(hash) || !isValidHex(pubKey)) return null
    return ScannedIdentity(hash.lowercase(), pubKey.lowercase())
}
